### ISSUE TITLE
A new version of the upstream code for this aggregator is out...

### ISSUE THREAD

**Issue by dirkhh** [sdr-enthusiasts/docker-radar1090#4]
To quote Mike:

    https://1090mhz.uk/files/radar-1.01/tar.gz

as/when/if you get time to update the containers ...

RSSI and MLAT were in the wrong order in the sender and aggregator - so it worked but shouldn't have - now fixed in sender and aggregator properly.

Another tweak is to make it spin trying DNS lookups indefinitely because some senders that had power cuts had their FR24 feed come back ok but 1090UK feed dropped out - reason was slow broadband recovery and my sender timed out and exited before the broadband was back.  Now fixed.

**Comment by kx1t** [comment]
I have updated the build script (https://github.com/sdr-enthusiasts/docker-radar1090/commit/5ee1325c8aecfe018f6a87a937861464e725872f) to point at the (hopefully stable) source location of `radar-1.01.tar.gz` and successfully rebuilt the container. 

Is that all we need to do? As in, these issues were fixed by Mike in his binary, and the latest source package contains the fixes?

(I've pinged Mike separately about this as well)
